### ISSUE TITLE
GitHub build workflow for simpler user experimentation

### ISSUE THREAD

**Issue by vadimkantorov** [xiph/opus-tools#83]
Could be sth like:
```yaml
name: buildopusenc
on: workflow_dispatch
jobs:

  buildopusenc:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Prerequisites
        run:  sudo apt-get update && sudo apt-get install -y git autoconf gcc libtool make libogg-dev libopus-dev libopusfile-dev libflac-dev libpcap-dev xz-utils zip

      - name: Clone
        run: |
          git clone https://github.com/xiph/libopusenc
          git clone https://github.com/xiph/opus-tools

      - name: Build
        run: |
          cd libopusenc
          bash ./autogen.sh
          bash ./configure --prefix="$(pwd)/../build"
          make check
          make install
          export PKG_CONFIG_PATH="$(pwd)/../build/lib/pkgconfig"
          cd ../opus-tools
          bash ./autogen.sh
          bash ./configure --prefix="$(pwd)/../build"
          make check
          make install

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
```
